### ISSUE TITLE
Build failure on OpenBSD-5.6

### ISSUE THREAD

**Issue by PHHargrove** [Intrepid/llvm-upc#11]
My builds on OpenBSD are now failing as follows:

```
llvm[1]: Compiling Watchdog.cpp for Release+Asserts build
In file included from /home/phargrov/upcnightly/llvm-upc/src/lib/Support/Unix/Watchdog.inc:15:0,
                 from /home/phargrov/upcnightly/llvm-upc/src/lib/Support/Watchdog.cpp:19:
/usr/include/unistd.h:527:18: error: 'fd_set' has not been declared
 int  select(int, fd_set *, fd_set *, fd_set *, struct timeval *);
                  ^
/usr/include/unistd.h:527:28: error: 'fd_set' has not been declared
 int  select(int, fd_set *, fd_set *, fd_set *, struct timeval *);
                            ^
/usr/include/unistd.h:527:38: error: 'fd_set' has not been declared
 int  select(int, fd_set *, fd_set *, fd_set *, struct timeval *);
                                      ^
```

A recent man page for `select()` says
```
/* According to POSIX.1-2001 */
#include <sys/select.h>

/* According to earlier standards */
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
```

And it looks like the "earlier standards" incantation does not work on OpenBSD-5.6.

Since there is no HAVE_SYS_SELECT_H token in include/llvm/Config/config.h yet, I am not prepared to make the necessary changes on my own.  However, I've confirmed that including sys/select.h works.

**Comment by PHHargrove** [comment]
This failure is currently appearing only on x86 but not on amd64.

**Comment by PHHargrove** [comment]
This failure was resolved by updating the gcc-4.8 installation which was mistakenly "held back" to the version for OpenBSD-5.5 (0.1 behind).  It appears that gcc's "include-fixed" headers resolve this properly.

So, this was never an llvm issue.
